# Generated by Django 5.2.5 on 2025-08-11 07:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorconnection',
            old_name='from_Doctor',
            new_name='from_doctor',
        ),
        migrations.RenameField(
            model_name='doctorconnection',
            old_name='to_Doctor',
            new_name='to_doctor',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='comment',
        ),
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='doctorconnection',
            unique_together={('from_doctor', 'to_doctor')},
        ),
    ]
