# Generated by Django 5.2.5 on 2025-08-11 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_from_doctor_doctorconnection_from_doctor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Doctor',
            new_name='doctor',
        ),
    ]
